// Modal Types
export const LOGIN_MODAL = 'LOGIN_MODAL';
export const REGISTER_MODAL = 'REGISTER_MODAL';
export const FORGOT_PASSWORD_MODAL = 'FORGOT_PASSWORD_MODAL';
export const EMAIL_SENT_MODAL = 'EMAIL_SENT_MODAL';
export const CROP_MODAL = 'CROP_MODAL';
export const CONFIRM_MODAL = 'CONFIRM_MODAL';
export const STATE_MODAL = 'STATE_MODAL';

export const ALL_MODAL_TYPES = [
  LOGIN_MODAL,
  REGISTER_MODAL,
  FORGOT_PASSWORD_MODAL,
  EMAIL_SENT_MODAL,
  CROP_MODAL,
  CONFIRM_MODAL,
  STATE_MODAL,
];
