FROM node:14.1.0-alpine3.10

# bash needed to run wait-for.sh
RUN apk update && apk add bash && apk add --no-cache coreutils

WORKDIR /app

COPY package*.json ./

USER root

# Make sure knex is same version as knex in package.json
RUN npm install cross-env --global
RUN npm install --quiet

COPY . .
