FROM node:14.1.0-alpine3.10

# bash needed to run wait-for.sh
RUN apk update && apk add bash && apk add --no-cache coreutils

WORKDIR /app 

COPY package*.json ./

USER node

RUN npm install --quiet

COPY . .
RUN npm run build
